"""esquema inicial

Revision ID: 10778a0c9a74
Revises: 
Create Date: 2026-09-06 17:11:27.475616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10778a0c9a74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad',
    sa.Column('asignacion_id', sa.String(length=36), nullable=True),
    sa.Column('carril', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('marcador_reanudacion', sa.String(length=500), nullable=True),
    sa.Column('iniciada_en', sa.String(length=35), nullable=False),
    sa.Column('finalizada_en', sa.String(length=35), nullable=True),
    sa.Column('minutos_reales', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignacion',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('carril', sa.String(length=20), nullable=False),
    sa.Column('duracion_estimada_min', sa.Integer(), nullable=False),
    sa.Column('vencimiento', sa.String(length=10), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('indivisible', sa.Boolean(), nullable=False),
    sa.Column('dependencias', sa.JSON(), nullable=False),
    sa.Column('contexto', sa.String(length=500), nullable=True),
    sa.Column('iniciativa_id', sa.String(length=36), nullable=True),
    sa.Column('tramite_id', sa.String(length=36), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_revision', sa.String(length=10), nullable=True),
    sa.Column('fecha_pospuesto', sa.String(length=10), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bloque_agenda',
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('candidata_id', sa.String(length=36), nullable=True),
    sa.Column('inicio', sa.String(length=5), nullable=False),
    sa.Column('fin', sa.String(length=5), nullable=False),
    sa.Column('justificacion_codigo', sa.String(length=40), nullable=False),
    sa.Column('justificacion_texto', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('captura',
    sa.Column('texto', sa.String(length=2000), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.String(length=35), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion',
    sa.Column('buffer_absorcion_min', sa.Integer(), nullable=False),
    sa.Column('dias_revision_espera', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflicto',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('campo', sa.String(length=50), nullable=False),
    sa.Column('valor_ganador', sa.JSON(), nullable=False),
    sa.Column('device_ganador', sa.String(length=64), nullable=False),
    sa.Column('ts_ganador', sa.String(length=35), nullable=False),
    sa.Column('valor_perdedor', sa.JSON(), nullable=False),
    sa.Column('device_perdedor', sa.String(length=64), nullable=False),
    sa.Column('ts_perdedor', sa.String(length=35), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispositivo',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_dispositivo_sync',
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('ultimo_client_sequence', sa.Integer(), nullable=False),
    sa.Column('ultimo_server_seq_entregado', sa.Integer(), nullable=False),
    sa.Column('ultima_conexion_at', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('evento',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.String(length=35), nullable=False),
    sa.Column('recorded_at', sa.String(length=35), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('client_sequence', sa.Integer(), nullable=False),
    sa.Column('base_version', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('server_seq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('device_id', 'client_sequence', name='uq_evento_device_seq')
    )
    op.create_index(op.f('ix_evento_server_seq'), 'evento', ['server_seq'], unique=False)
    op.create_table('evento_fijo',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('inicio', sa.String(length=5), nullable=False),
    sa.Column('fin', sa.String(length=5), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativa',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('cuota_semanal_min', sa.Integer(), nullable=False),
    sa.Column('minutos_ejecutados_semana', sa.Integer(), nullable=False),
    sa.Column('deuda_min', sa.Integer(), nullable=False),
    sa.Column('semana_referencia', sa.String(length=8), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interrupcion',
    sa.Column('actividad_id', sa.String(length=36), nullable=False),
    sa.Column('marcador_reanudacion', sa.String(length=500), nullable=False),
    sa.Column('inicio', sa.String(length=35), nullable=False),
    sa.Column('fin', sa.String(length=35), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paso_tramite',
    sa.Column('tramite_id', sa.String(length=36), nullable=False),
    sa.Column('etapa_id', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('completado_en', sa.String(length=35), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguimiento',
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.String(length=36), nullable=False),
    sa.Column('fecha_revision', sa.String(length=10), nullable=False),
    sa.Column('notas', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_tramite',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('etapas', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tramite',
    sa.Column('tipo_tramite_id', sa.String(length=36), nullable=False),
    sa.Column('tipo_tramite_version', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('etapa_actual_id', sa.String(length=64), nullable=True),
    sa.Column('fecha_inicio', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('field_meta', sa.JSON(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tramite')
    op.drop_table('tipo_tramite')
    op.drop_table('seguimiento')
    op.drop_table('paso_tramite')
    op.drop_table('interrupcion')
    op.drop_table('iniciativa')
    op.drop_table('evento_fijo')
    op.drop_index(op.f('ix_evento_server_seq'), table_name='evento')
    op.drop_table('evento')
    op.drop_table('estado_dispositivo_sync')
    op.drop_table('dispositivo')
    op.drop_table('conflicto')
    op.drop_table('configuracion')
    op.drop_table('captura')
    op.drop_table('bloque_agenda')
    op.drop_table('asignacion')
    op.drop_table('actividad')
    # ### end Alembic commands ###
