"""sync cambio registro y secuencia global

Revision ID: 9c8a30e6a82d
Revises: 5c89b0486a29
Create Date: 2026-09-06 17:38:12.868223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8a30e6a82d'
down_revision: Union[str, None] = '5c89b0486a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cambio_registro',
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('client_sequence', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.String(length=35), nullable=False),
    sa.Column('base_version', sa.String(length=36), nullable=True),
    sa.Column('campos', sa.JSON(), nullable=False),
    sa.Column('campo_ts', sa.JSON(), nullable=False),
    sa.Column('server_seq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('change_id'),
    sa.UniqueConstraint('device_id', 'client_sequence', name='uq_cambio_device_seq')
    )
    op.create_index(op.f('ix_cambio_registro_server_seq'), 'cambio_registro', ['server_seq'], unique=False)
    op.create_table('secuencia_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secuencia_global')
    op.drop_index(op.f('ix_cambio_registro_server_seq'), table_name='cambio_registro')
    op.drop_table('cambio_registro')
    # ### end Alembic commands ###
